# Generated by Django 5.0.3 on 2024-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
