# Generated by Django 5.0.3 on 2024-09-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0002_carouselimage_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='image',
            new_name='desktop_image',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='carousel/mobile/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
