# Generated by Django 5.0.3 on 2024-09-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0003_rename_image_carouselimage_desktop_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='album_covers/')),
            ],
        ),
    ]
