# Generated by Django 5.0.3 on 2024-09-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0004_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('release_date', models.DateField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='album_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('genres', models.ManyToManyField(related_name='songs', to='navio_naranja_app.genre')),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='product',
            name='songs',
            field=models.ManyToManyField(related_name='products', to='navio_naranja_app.song'),
        ),
    ]
