# Generated by Django 5.0.3 on 2024-09-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0005_genre_product_song_delete_album_product_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
