# Generated by Django 5.0.3 on 2024-11-03 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0008_purchase_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='unique_id',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navio_naranja_app.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navio_naranja_app.purchase')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
