# Generated by Django 5.0.3 on 2024-11-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navio_naranja_app', '0010_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
